<a href="https://colab.research.google.com/github/Prattoypaul/deeplearning/blob/machinel/Bigdata_lLAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np


In [5]:
data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Big data lab/sample.csv")

In [6]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [7]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [8]:
x=data.drop('Purchased',axis=1)
y=data['Purchased']

In [9]:
x.head()

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
from pandas.core import missing
simp=SimpleImputer(missing_values=np.nan,strategy="mean")

In [12]:
x=x.values
y=y.values

In [13]:
x[:,1:3]=simp.fit_transform(x[:,1:3])

In [14]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])

In [17]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [18]:
y=le.fit_transform(y)

In [19]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [21]:
transformer=ColumnTransformer([('nor1',OneHotEncoder(),[0])],remainder='passthrough')

In [22]:
x=transformer.fit_transform(x)

In [23]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [30]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler=StandardScaler()

In [31]:
x[:,3:5]=scaler.fit_transform(x[:,3:5])

In [32]:
x

array([[1.0, 0.0, 0.0, 0.7588743615900194, 0.7494732544921666],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687536],
       [0.0, 1.0, 0.0, -1.2755547779917338, -0.8912654918285231],
       [0.0, 0.0, 1.0, -0.11302384108787494, -0.25320042381492136],
       [0.0, 1.0, 0.0, 0.1776088931380896, -1.7709863242942932e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350369],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752667],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.387538322505769],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.752146932799256],
       [1.0, 0.0, 0.0, -0.25834020820085724, 0.29371249162530827]],
      dtype=object)

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [35]:
xtrain

array([[0.0, 0.0, 1.0, 0.0, -1.0735697969752667],
       [0.0, 1.0, 0.0, 0.1776088931380896, -1.7709863242942932e-16],
       [1.0, 0.0, 0.0, 0.7588743615900194, 0.7494732544921666],
       [0.0, 0.0, 1.0, -0.11302384108787494, -0.25320042381492136],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687536],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.387538322505769],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.752146932799256],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350369]],
      dtype=object)

In [41]:
print('preprocessed data')
xtrain

preprocessed data


array([[0.0, 0.0, 1.0, 0.0, -1.0735697969752667],
       [0.0, 1.0, 0.0, 0.1776088931380896, -1.7709863242942932e-16],
       [1.0, 0.0, 0.0, 0.7588743615900194, 0.7494732544921666],
       [0.0, 0.0, 1.0, -0.11302384108787494, -0.25320042381492136],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687536],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.387538322505769],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.752146932799256],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350369]],
      dtype=object)

In [39]:
print('orginal_data')
data

orginal_data


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes