<a href="https://colab.research.google.com/github/Prattoypaul/deeplearning/blob/machinel/nlp15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/nlp cODE/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(df.Message,df.spam,test_size=0.2)

In [ ]:
xtrain.shape

(4457,)

In [ ]:
xtest.shape

(1115,)

In [ ]:
type(xtest)

pandas.core.series.Series

In [ ]:
type(xtest.values)

numpy.ndarray

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [ ]:
xtrain_cv=cv.fit_transform(xtrain.values)

In [ ]:
xtrain_cv

<4457x7851 sparse matrix of type '<class 'numpy.int64'>'
	with 59259 stored elements in Compressed Sparse Row format>

In [ ]:
xtrain_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
xtrain_cv.shape

(4457, 7851)

In [ ]:
cv.get_feature_names_out()[1000]

'anonymous'

In [ ]:
xtrain_np=xtrain_cv.toarray()
xtrain_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(xtrain_np[0]!=0)

(array([ 938, 1021, 1677, 2427, 3464, 3666, 4806, 4872, 6624, 6626, 7024,
        7651, 7808, 7814]),)

In [ ]:
xtrain_np[0][938]

1

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(xtrain_cv,ytrain)

MultinomialNB()

In [ ]:
xtest_cv=cv.transform(xtest)

In [ ]:
from sklearn.metrics import classification_report
y_pred=model.predict(xtest_cv)

In [ ]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       964
           1       0.98      0.90      0.94       151

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [ ]:
email_cv=cv.transform(emails)

In [ ]:
model.predict(email_cv)

array([0, 1])

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
clf=Pipeline([
                               ('vectorizer',CountVectorizer()),
                               ('nb',MultinomialNB())
])

In [ ]:
clf.fit(xtrain,ytrain)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
ypred=clf.predict(xtest)

In [ ]:
from inspect import classify_class_attrs
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       964
           1       0.98      0.90      0.94       151

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
clf.predict(emails)

array([0, 1])